import Testing

@testable import AdventOfCode

struct Year2025Day07Tests {
  let testData = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

  @Test func testPart1() async throws {
    let challenge = Year2025.Day07(data: testData)
    #expect(challenge.part1() == 21)
  }

  @Test func testPart2() async throws {
    let challenge = Year2025.Day07(data: testData)
    #expect(challenge.part2() == 40)
  }
}
